
# docker build -f Dockerfile-installed-bionic -t projetsim/sim-node-local .

# -------------=== cartp rust build ===-------------
FROM ubuntu:bionic as substrate-node-sim-builder

RUN apt-get update \
 && apt-get install -y \
 curl \
 build-essential \
 llvm \
 clang \
 libudev-dev \
 libssl-dev

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y 

ENV PATH=$PATH:/root/.cargo/bin

RUN rustup default stable
RUN rustup update
RUN rustup update nightly
RUN rustup target add wasm32-unknown-unknown --toolchain nightly

COPY . /project

WORKDIR /project/

# RUN cargo update -p parity-db
# RUN cargo update -p prost-derive
RUN apt install -y protobuf-compiler

RUN cargo build --release

# RUN cargo install cargo-deb
# RUN cargo deb -p node-template

# # -------------=== cartp rust docker build ===-------------
# FROM ubuntu:bionic

# COPY --from=substrate-node-sim-builder /project/target/debian/node-template_*.deb /tmp

# RUN apt-get update \
#  && dpkg -i /tmp/node-template_*.deb || true \
#  && apt-get -f -y install

# RUN node-template --help

# RUN echo "Executable available using: node-template <OPTIONS>"