{
 "title": "Substrate Node Template Metrics",
 "description": "Grafana dashboard for substrate template metrics. Instructions on use: https://substrate.dev/docs/en/tutorials/visualize-node-metrics/",
 "tags": [
  "substrate",
  "blockchain",
  "node",
  "template",
  "polkadot",
  "kusama"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "chaintype",
    "label": "Chain Type",
    "query": "relaychain, insurance-parachain, renault-parachain, local, substrate"
   }
  ]
 },
 "panels": [
  { "title": "Node/chain data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Block Height (best)",
   "type": "graph",
   "description": "What your node sees as the highest block (NOT finalized)",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_block_height{status=\"best\", instance=~\".*$chaintype.*\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{job}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Block Height (finalized)",
   "type": "graph",
   "description": "What your node sees as the highest finalized block ( less than or equal to best)",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_block_height{status=\"finalized\", instance=~\".*$chaintype.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Block Height (best) rate (block/min)",
   "type": "graph",
   "description": "What your node sees as the highest block (NOT finalized)",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(substrate_block_height{status=\"best\", instance=~\".*$chaintype.*\"}[$__interval]))*60",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "global rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Block Height (finalized) rate (block/min)",
   "type": "graph",
   "description": "What your node sees as the highest finalized block ( less than or equal to best)",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(substrate_block_height{status=\"finalized\", instance=~\".*$chaintype.*\"}[$__interval]))*60",
     "legendFormat": "global rate"
    }
   ]
  },
  {
   "title": "Finished tx/sec",
   "type": "graph",
   "description": "Total transactions that finished validation",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(substrate_sub_txpool_validations_finished{instance=~\".*$chaintype.*\"}[$__interval])",
     "legendFormat": "{{job}} rate"
    },
    {
     "expr": "avg(rate(substrate_sub_txpool_validations_finished{instance=~\".*$chaintype.*\"}[$__interval]))",
     "legendFormat": "tot avg rate"
    }
   ]
  },
  {
   "title": "Submitted tx/sec",
   "type": "graph",
   "description": "Total transactions that were submitted for validation",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(substrate_sub_txpool_submitted_transactions{instance=~\".*$chaintype.*\"}[$__interval]))",
     "legendFormat": "avg rate submitted tx"
    },
    {
     "expr": "rate(substrate_sub_txpool_submitted_transactions{instance=~\".*$chaintype.*\"}[$__interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Ready Queue size",
   "type": "graph",
   "description": "Ready Queue - Contains transactions that can be included in a new pending block. For runtimes built with FRAME, the transactions must follow the exact order in the ready queue.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "substrate_ready_transactions_number{instance=~\".*$chaintype.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Tx invalid rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(substrate_sub_txpool_validations_invalid{instance=~\".*$chaintype.*\"}[$__interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total finished tx ",
   "type": "graph",
   "description": "Total transactions that finished validation",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_sub_txpool_validations_finished{instance=~\".*$chaintype.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total submitted tx ",
   "type": "graph",
   "description": "Total transactions that were submitted for validation",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_sub_txpool_submitted_transactions{instance=~\".*$chaintype.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Sum of finished tx ",
   "type": "graph",
   "description": "Total transactions that finished validation",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(substrate_sub_txpool_validations_finished{instance=~\".*$chaintype.*\"})",
     "legendFormat": "sum finished"
    }
   ]
  },
  {
   "title": "Sum of submitted tx ",
   "type": "graph",
   "description": "Total transactions that were submitted for validation",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(substrate_sub_txpool_submitted_transactions{instance=~\".*$chaintype.*\"})",
     "legendFormat": "Sum submitted"
    }
   ]
  },
  {
   "title": "Tx invalid",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "substrate_sub_txpool_validations_invalid{instance=~\".*$chaintype.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Tx queue process failed rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(substrate_import_queue_processed_total{result=\"failed\"}[$__interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Tx queue process success rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(substrate_import_queue_processed_total{result=\"success\"}[$__interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Task rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(substrate_tasks_spawned_total[$__interval])",
     "legendFormat": "{{job}} {{task_name}}"
    }
   ]
  },
  {
   "title": "Nodes info",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
   "targets": [
    { "expr": "substrate_build_info" }
   ]
  },
  { "title": "P2P/communication information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "RPC calls",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(substrate_rpc_calls_total[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "P2P requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(substrate_sub_libp2p_requests_out_success_total_sum)",
     "legendFormat": "sum out request count"
    },
    {
     "expr": "sum(substrate_sub_libp2p_requests_in_success_total_sum)",
     "legendFormat": "sum in request count"
    }
   ]
  },
  {
   "title": "Proposer Block Construction Time",
   "type": "graph",
   "description": "histogram 90th quantiles for time to construct a block (seconds) More info: https://prometheus.io/docs/prometheus/latest/querying/functions/#histogram_quantile",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short", "label": "Time (s)" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(substrate_proposer_block_constructed_bucket[5m])) by (le))",
     "legendFormat": "90th quantile for block construction time (s)"
    }
   ]
  },
  {
   "title": "State Cashe (bytes)",
   "type": "graph",
   "description": "What your node sees as the highest finalized block ( less than or equal to best)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "substrate_state_cache_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "LibP2P peers",
   "type": "graph",
   "description": "Number of connected peers",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_sub_libp2p_peers_count",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}